version: "3.8"

services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "28000:8000/tcp"
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/dogmamgod
    ports:
      - "7474:7474"
      - "7687:7687"
