name: CI
on:
  push:
  pull_request:
  schedule:
  - cron: 0 14 * * 0
jobs:
  test:
    name: Make
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb
        ports:
        - 3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: dogmatiq
          MYSQL_USER: dogmatiq
          MYSQL_PASSWORD: dogmatiq
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Checkout
      uses: actions/checkout@v1
    - name: Make
      run: make ci
      env:
        DOGMATIQ_TEST_MYSQL_DSN: "root:rootpass@tcp(127.0.0.1:${{ job.services.mariadb.ports['3306'] }})/dogmatiq"
    - name: Upload Coverage Reports
      if: success()
      run: bash <(curl -s https://codecov.io/bash) -t "$TOKEN" -B "${{ github.ref }}"
      env:
        TOKEN: "${{ secrets.CODECOV_TOKEN }}"
